kind: Service
apiVersion: v1
metadata:
  name: redis-svc
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
